### ISSUE TITLE
Patch failed, cybdata4.rbx only

### ISSUE THREAD

**Issue by legraf** [juanitogan/rbxit#1]
First: thanks so much for attempting this!  You're a hero.
Second: but, it didn't work.  :)

I'll paste the full output from the patcher below, but first the basic specs:
Win7 64-bit Ultimate.
US version 1.10a
Files sizes were as shown in your post for the USA version, but I note my cybdata4.rbx modify time is one hour earlier (perhaps a timezone/daylight savings thing?)
‎June ‎12, ‎1996, ‏‎11:32:16

Now the output:

xdelta3: source F:\games\cyberstorm\CYBDATA2.RBX source size 14.6 MiB [15306390]
 blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 941 B: out 8.00 MiB: total in 941 B: out 8.00 MiB: 400 ms
xdelta3: 1: in 3.29 MiB: out 8.00 MiB: total in 3.29 MiB: out 16.0 MiB: 874 ms
xdelta3: 2: in 3.54 MiB: out 4.13 MiB: total in 6.83 MiB: out 20.1 MiB: 890 ms
xdelta3: finished in 2.2 sec; input 7157930 output 21107994 bytes (294.89%)
xdelta3: source F:\games\cyberstorm\CYBDATA3.RBX source size 16.0 MiB [16805969]
 blksize 64.0 MiB window 64.0 MiB
xdelta3: 0: in 1.16 KiB: out 8.00 MiB: total in 1.16 KiB: out 8.00 MiB: 430 ms
xdelta3: 1: in 5.57 MiB: out 8.00 MiB: total in 5.57 MiB: out 16.0 MiB: 1.4 sec
xdelta3: 2: in 7.14 MiB: out 8.00 MiB: total in 12.7 MiB: out 24.0 MiB: 1.9 sec
xdelta3: 3: in 7.08 MiB: out 8.00 MiB: total in 19.8 MiB: out 32.0 MiB: 1.9 sec
xdelta3: 4: in 711 KiB: out 1.54 MiB: total in 20.5 MiB: out 33.5 MiB: 178 ms
xdelta3: finished in 5.8 sec; input 21478548 output 35168363 bytes (163.74%)
xdelta3: source F:\games\cyberstorm\CYBDATA4.RBX source size 157 MiB [165223668]
 blksize 2.00 MiB window 64.0 MiB
xdelta3: 0: in 724 B: out 8.00 MiB: total in 724 B: out 8.00 MiB: 1.6 sec
xdelta3: 1: in 28.0 B: out 8.00 MiB: total in 752 B: out 16.0 MiB: 55 ms
xdelta3: 2: in 28.0 B: out 8.00 MiB: total in 780 B: out 24.0 MiB: 45 ms
xdelta3: 3: in 28.0 B: out 8.00 MiB: total in 808 B: out 32.0 MiB: 60 ms
xdelta3: 4: in 28.0 B: out 8.00 MiB: total in 836 B: out 40.0 MiB: 43 ms
xdelta3: 5: in 28.0 B: out 8.00 MiB: total in 864 B: out 48.0 MiB: 45 ms
xdelta3: 6: in 28.0 B: out 8.00 MiB: total in 892 B: out 56.0 MiB: 44 ms
xdelta3: 7: in 28.0 B: out 8.00 MiB: total in 920 B: out 64.0 MiB: 44 ms
xdelta3: 8: in 28.0 B: out 8.00 MiB: total in 948 B: out 72.0 MiB: 49 ms
xdelta3: 9: in 28.0 B: out 8.00 MiB: total in 976 B: out 80.0 MiB: 288 ms
xdelta3: 10: in 28.0 B: out 8.00 MiB: total in 0.98 KiB: out 88.0 MiB: 220 ms
xdelta3: 11: in 28.0 B: out 8.00 MiB: total in 1.01 KiB: out 96.0 MiB: 273 ms
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!! Error during audio file patching                      !!!
!!! Maybe already patched, wrong region, or unknown print !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by juanitogan** [comment]
Thanks for the perfect report.  Interesting, but my files are now reporting as 11:xx AM as well.  That was in the winter and in a different time zone so I guess the times adjust.  I hadn't realized Windows was doing that now.  That, or I got it wrong in the first place.  But it adds up, I went back 2 times zones +1 for DST.  12-2+1=11.  I'll think I'll note this in the wiki.

Anyway, to the real deal.  Thanks for reporting this.  Someone else reported a problem with file 4 but I was moving and didn't follow up till a month later and haven't heard since.  Now knowing it is a US copy, you made me curious, so I checked 3 more of my copies for the variance but couldn't find it.  I have more unopened copies but won't bother with those yet (I went shopping for cheap copies after my first patch using a borrowed copy).  I note, however, one of my unopened boxes is a Sierra 3-pack called _Strategy: 3 Games of Power and Glory_.  I wonder if that print is the odd one.  Do you know if your copy came from anything other than the original packaging such as this 3-pack?

Anyhow, I need a copy of your CYBDATA4.RBX to build a patch for it.  It may take a little while to work up because, as you probably read, I'm tired of making people try the two versions (US and EU) and want to make a unified patcher.  This means much more testing.  Boring.  This also means a much bigger patch file but I doubt anyone cares about that.

The easiest way for you to share that file with me is to put it on DropBox, OneDrive, Google Drive, or whatever works for you, and share the link to it here.  Once I download it, you can tear down the link if you like.

If that doesn't work for you, I can email you at the address you used to post on my Wordpress blog but I doubt the file will fit through our email services without you chopping it up into smaller pieces.

Thanks again,
Matt

**Comment by legraf** [comment]
Thank you, Matt, for the super-quick and clear reply.  I can't be 100% certain about the original packaging; I have two Cyberstorm CDs, and these files have been on my HD for so long, I wasn't sure which they came from.  For what it's worth, I suspect it was purchased in Canada.
Stupidly, I grabbed the one CD I could find and copied the .rbx files again to give this another try... and it worked.  Yay, for me.  But this doesn't help you, as I didn't make a copy of CYBDATA4.RBX first, so it has been overwritten.  It must have come from the other CD, which is surely in a box ... somewhere.
If I can find the other, I'll install that and see if I can reproduce the problem.  Otherwise ... sorry, but it's working brilliantly (minus the save/load issue, I'm off to get DxWnd working now).

**Comment by juanitogan** [comment]
Foiled again!  Fair enough, though.  Glad you got past the patch install.  I hope DxWnd works for you.

Who knows.  Maybe it was a red herring and your file 4 was simply corrupted.  I think I'll name my new company File 4 in honor of this pursuit.  I hope to hear from you in case you do find another version of file 4.

**Comment by juanitogan** [comment]
I have no explanation for this particular trouble with file 4 (wrong date and time to be the crack version), but similar trouble reported by Rick ages ago with file 4 has since been proven to be a version of file 4 created as part of a CyberStorm crack by Hybrid (from Finland?).  A version I will not support.  Hybrid is possibly also this user:

https://www.facebook.com/Hybrid-Ripper-293656847469442/

Anyhow, closing this due to likely corruption or possible xdelta3 error (it's happened), and no longer looking for that unknown print of file 4 (which is now known).
