### ISSUE TITLE
Where is Full-Screen Setting & customizing Mouse

### ISSUE THREAD

**Issue by dig314** [juanitogan/rbxit#11]
Greetings. Thank you for the CyberStorm update! 

 Where is the setting for  full-screen mode vs Windowed mode ?  

 Is there a way to customize the mouse buttons ?

The text below is for  AutoHotKey  for a 5 button mouse. 
( * Install AutoHotKey  )
( * paste text below into new text file )
( * save text file and rename extension to .AHK )
( * double-click .AHK file before Starting CyberStorm )

#SingleInstance Force
#NoEnv
#MaxHotkeysPerInterval 9999999
#HotkeyInterval 9999999
#KeyHistory 0
#UseHook On
ListLines Off
SetBatchLines, -1
SetKeyDelay, -1, -1
SetMouseDelay, -1
SetDefaultMouseSpeed, 0
SetWinDelay, -1
SetControlDelay, -1
SendMode Input

#IfWinActive, ahk_exe CSTORM.exe

;https://autohotkey.com/docs/KeyList.htm
*MButton::K                   ; Middle Button = Crouch
*XButton1::>                  ; Thumb Button = Next Unit
*XButton2::<                  ; Thumb Button = Prev Unit
*WheelDown::NumpadSub         ; Scrool Wheel = Zoom Out
*WheelUp::NumpadAdd           ; Scroll Wheel = Zoom In

#UseHook Off

**Comment by juanitogan** [comment]
To quote the install instructions:

- ... set the in-game preferences to one of these two options (requires game restart):
  - Run in full-screen mode (recommended):
    - [x] Game always fills entire screen
      - [x] Use extra screen real-estate for battle terrain
  - Run in windowed mode and maximize the window before launching a mission (risky because only certain window sizes will render correctly):
    - [ ] Game always fills entire screen
      - [x] _Use extra screen real-estate for battle terrain_

So, File >> Prefs >> Windows tab -- guess I need to update the wiki to make that even more clear.  I've seen nothing on mouse options; you're on your own there.
