### ISSUE TITLE
Patch fails for german version of 3D Ultra Minigolf Deluxe

### ISSUE THREAD

**Issue by senolfeldmann** [juanitogan/rbxit#4]
Hi Mr. Jernigan,

first of all, thank you for your outstanding work. IT IS SIMPLY AMAZING WHAT YOU ACCOMPLISHED. I tried to get to run this on Win Vista+ for several years, but got distracted by university...

Anyhow, the patch does not work with the german version of 3D Ultra Minigolf Deluxe. Is there any way I could upload you the files for examination?
Thank you for your attention.
Best Regards

**Comment by juanitogan** [comment]
Yes, please make a copy of the MiniGolf folder from your CD.  Zip it, Rar it, whatever... and upload it somewhere such as Dropbox, Google drive, Onedrive, or wherever you can share a link from.

Thank you for your willingness to help.

**Comment by senolfeldmann** [comment]
I also had a copy of "3D Ultra Pinball: The Lost Continent" in german, so I uploaded them both on my dropbox. I don't play the pinball game, but maybe there will be other users who can benefit from this:

https://dl.dropboxusercontent.com/u/23427182/MG_DLX.ISO
https://dl.dropboxusercontent.com/u/23427182/PINBALL3.ISO

Best Regards
lones710

And again, thank you for your amazing work.

**Comment by juanitogan** [comment]
Thanks for the ISOs.  I filed the pinball one away with my other pinball discs in case a need for the German copy ever comes up.

I've wrapped up a new patch release for MiniGolf.  Hopefully this is the last one for Deluxe with 3 editions now covered.  Thank you, again, for the help and the encouraging words.  I'm glad that my work is being used.

Here's link to the new release.  It's pretty fat at 440 MB now.

https://github.com/juanitogan/rbxit/releases/download/3dumgd.patch.r4/3DUltraMiniGolfDeluxe-20-Win7fix.r4.exe

Let me know how it goes.

Matt

**Comment by senolfeldmann** [comment]
IT WORKS. YOU ARE AMAZING! One suggestion: wouldn't it be more convenient for people with a slow internet connection to make seperate patches for the different regional versions?

**Comment by juanitogan** [comment]
That's a totally valid and good suggestion -- and one I think about often.  I used to do that, because it was easier to build and test that way, but have moved away from it.  If you look at the Cyberstorm patch, you will see it is still divided between the US and Europe -- yet, I keep itching for someone to find a new version so I have an excuse to combine them.

This will be a longer explanation than you need but I feel like writing it for whoever cares to read it.  It is not meant to be a lecture; it is simply interesting for me to think about what people need and why.

People need simplicity.  The days of slow internet are rapidly ending.  Also, pain is relative to thresholds.  If 200 MB is already very painful due to a slow connection, 400 MB isn't much more painful, given no choice between the two (you, unfortunately, saw both sides of that and now have it stuck in your head).  More importantly, however, when one patch fails -- for any reason -- people invariably download the other and try it.  This extra variable leads to complications for both them and me, that may or may not be related to the patch.  Thus, fewer patchers means less time wasted on my end and, occasionally, less time wasted on the user's end.  In short, because I do this for free, with little benefit to myself (I have little time or opportunity for gaming for reasons I won't get into) I get to put some of the burden on you by keeping my end as simple as I need.  If I were being paid for this, or if these were more popular, or if this was 15 years ago, I might do it different.

Now, in spite of all that, when the German-language editions came along, I had to rethink it all over again.  I was very tempted to put all the English versions here, and the German ones there.  Surely, people would not mix those up, right?  In the end I decided it would still cause problems here and there -- because communication always fails somewhere -- and simplicity and tomorrow's internet speeds won out.  I may change that decision again someday, but I doubt it.

The more interesting question to me, to beat you to it, is: Why not build it different?  When I first succeeded with Cyberstorm (which was an amazing feeling) I was anxious to get it out.  I knew I had 3 basic options: 1) distribute the RBX files already patched (very very fat, among other potential issues, but very easy); 2) distribute patch delta files to the RBX files (what I do now, and it took some effort to optimize for this much and type of data); or 3) write a patch script to process all the audio data in place on the user's machine.  That last option is very appealing because then the patcher would be tiny and possibly universal.  The drawbacks, however, are that it would have taken much longer to prepare and that the more tech you run, the more risk you take on with various machines (even my current use of the Xdelta3 patcher fails on some machines).  Considering some of the tools are my own and untested in the world at large, that is a lot of risk.  All things I don't have time for.  Furthermore, it couldn't really be universal because some users have corrupt RBX files and the only way to account for that is to maintain of checksum catalog of valid RBX files (a feature already built into the patch files).  Without that knowledge, support is more time consuming.  Thus, I would still be stuck making new releases whenever someone finds a new valid RBX.  If, however, I was being paid to produce a professional patch, this is the route I would go (but if I were being paid, I would probably also have the source code to the game executables and could maybe fix or workaround the problems there instead of rewriting the audio data into this more supported format [which, well, is not a bad idea no matter what]).

Anyhow, thanks again for the help and keep the suggestions coming.
