### ISSUE TITLE
"Homebrew" Mod/Patch 1.2 for Cyberstorm

### ISSUE THREAD

**Issue by ScarabParamit** [juanitogan/rbxit#5]
Hello there...sober creative!
Just found this topic trying to figure out how to run Cyberstorm on Win7. Thank you for all help.
Now is my time to return the favor, ammong countless (aparently still usless) things i saved from web i'm happy work of this (at least) one guy can now resurface...to bring happy and joy.

I have this Mod, and also a die-hard-elite fan who even if is not a creator himself, did share a nice guide.

http://www.mediafire.com/file/9mjbhaunrxu2rrm/Cyberstorm_Missionforce_Patch_1.1_1.2_MOD_Guide.zip

Write to me on SanSui@Protonmail.com if you have any questions...or seek something without hope - one might never know.

Regards!

**Comment by ScarabParamit** [comment]
B.t.w ...as i encountered:

"Error during compatibility database install   !!!
!!! Please report any message seen above          !!!
!!! Perhaps sdbinst.exe does not exist on this OS !!!
!!!   or it was blocked from executing"

could you please be so kind...and provide me with already set-up game (ziped directory)? ...exept if your patch edit .exe file i will wait until you make 1.2 mod included.

Regards!

**Comment by juanitogan** [comment]
Dude!  You rule!  Thanks much for 1.2. 👍✖️💯  I'll add it to the site soon.

Sorry to hear about the SDB error.  First I've seen it, that I recall, even though I wrote code to expect it.  I really need to see any messages before that, if any.  But what it probably means is what it says, that `sdbinst.exe` is not on your system or is blocked because you are not logged in as an admin.  Try running `sdbinst -?` from the command prompt as an admin and see what it says.  It might have something to do with the version of Win7, SP1, etc.

Anyhow, it doesn't really matter in Win7 because the SDB doesn't fix the Save/Load problem on Win7 and you need launch with DxWnd instead.  The RBX files were already patched for the audio bug before the SDB error, so you should be good to go.

I looked at the 1.2 exe and it should not interfere with any of this.  I do not patch the exe and the metadata in it is the same as the 1.0 and 1.1 exes.

**Comment by ScarabParamit** [comment]
I think problem is linked to my Win 7 ver...its a custom community build/mod - if anything its either that or some third party conflict.

Happy i could help. I hate when things go to waste, so I would "rule" if i did release at least half of mods i made myself - but at least i saved 

this one. Still not gave up on massive Evil Genius project.

P.S. Thanks for info about DxWnd...
Have you tried Enemy Infestation? DXwnd works wonders! All its needed is to set:
Generic:
Run in Window
Terminate on window close
Position:
(monitor whole) Desktop
Hide desktop background
and if someone choose keep aspect ratio
Colors are fixed and game look and runs like a charm!

Regards! =)

**Comment by juanitogan** [comment]
Glad to hear you got it running.  Yeah, there are plenty of different DxWnd settings that will get you running.  After a few days of testing it to death, I listed the set that will work with the most users in the most scenarios with the fewest little quirks.

I haven't tried Enemy Infestation (or Evil Genius).  I find very little time or opportunity for gaming.  Mostly just building and fixing things.  I encourage you to finish your Evil Genius project.

**Comment by ScarabParamit** [comment]
Thanks! This topic can be closed now.

P.S. I advice you stop from time to time and "eat fruits of your labour" ...before they spoil. I also mod  and fix like crazy in artifficial and real life...and its burns down if you don't get anything from it.
Well...creation is kind of a prayer and relax/a hobby if none strings are attacherd, creation with intent to achive some direct goals is borders with production that can drive into mental anxiety, stress if forced to get results. Main couse of unfinished projects for me. It need to be a fun - always - it can be a job to...but not "just"...same with gaming where you have to grind - its burning down. I see you have Earthsiege 2 here? Play it, get to the mission with first aircraft and have fun! =P

Evil Genius is like Dungeon Keeper on steroids ...but in more like James Bond climate. I needs a a lot of tweaks to make it realy enjoyable, so you can either use massive mod provided on nexus (i think...recently someone else finished their project - cummulative forum mods in one with tweaks) or wait, i will deliver it someday and its gonna be something "more" xD =P

Enemy Infestation is like S-F tactical x-com/fallout tactics in realtime - unique in a way, i have to play it meself some more. Atmosphere is good.

* One more thing...if you alredy have few old games about Cybrids like Cyberstorm or Earthsiege 2... there is a game called Starsiege, i remember a lot of topics about people complaining like crazy about lack of in-game-music in one and only properly working version called "Starsiege Complete" thats a fan/community restoration project making it work on any machine. I found out by semi-accident how to make music work!
In main folder there is a file called "defaultPrefs.cs"
Inside whats need to be changed is
"$pref::playShellMusic = "False";
to
$pref::playShellMusic = "True";
You ever make a topic about this GEM remember about this. I also provide with full legit release if you can't find this working one ( "Starsiege Complete.exe" ).
There is a old-fan forums relesing their own version with music working but broken everything else in the game - wach out, its called ( "SSINSTALL-ALL.exe" ).

Regards!

**Comment by juanitogan** [comment]
Thanks for the hints on Starsiege.  I might take a look at it after I wrap up some other projects.  It is one of the free TRIBES-related games you can download from Hi-Rez, so it should be easy to grab and check out.  If I can't find the mods, I'll ping you.

I find the most joy in bringing happiness to others.  So, wrapping up a project and pushing it out (perfected or not, even though my nature is to be a perfectionist) is usually sufficient joy for me.  Otherwise, I am primarily a social gamer, and so gaming often depends on the schedules of others around me and other life events out of my control.  My projects, however, I get to control those pretty well (as long as I don't fall into project-switching-hell, which is easy to fall into).

Thanks again,
Matt
