### ISSUE TITLE
Unable to save Mission Force.

### ISSUE THREAD

**Issue by MsSheare** [juanitogan/rbxit#8]
Okay I have about given up trying to get this game to save. I keep getting a Error code then the game fails.

The Instruction at 10019586 referenced at 00000000
the memory could not be read from

click okay to terminate the application

**Comment by TheRaccoonKing** [comment]
MsSheare, same here.

I've tried and tried.  More reboots, reinstalls, and recleanings than I can count.  No dice.

I think we've screwed ourselves by messing with the compatibility settings before hand.  It seems there's no help for us now.

Sad day.

**Comment by juanitogan** [comment]
@MsSheare - I need intel about your OS and what you've tried if you want any hope of help.  Read the install wiki and, especially, the troubleshooting section that covers this.

@TheRaccoonKing - From our last exchange on the blog site I know you read all that already.  I feel your pain.  What I should probably do for people in your predicament is write a registry scrubber to help you get back to zero, but 1) that is only assuming the pre-patching registry entries are the problem, and 2) I don't have time to get into that huge task right now, if ever (I'm burning down savings while working on my own game).  If you care for a long-shot effort that comes with its own set of pain, DxWnd implements a different method for getting around the load and save crashing.  It's just that the last time I tested it on Windows 10 it presented other UI problems that would have generated a whole new set of complaints so I can't recommend it as a general option.  I would guess that there are good odds that DxWnd has fixed those problems by now but I don't know.  Anyhow, if you care to test it, follow the same basic DxWnd instructions I have for the other versions of Windows.

**Comment by MsSheare** [comment]
Hi sorry about not getting back in time the holiday is keeping me busy.  I have a Del  Optiplex 750  I couldn't even get the game to install  the normal way so I ran the patch and that did get it working  the folder containing the game is on the desk top. Beyond that I have done nothing else.

________________________________

**Comment by juanitogan** [comment]
It appears you didn't follow the install instructions on the wiki correctly.  My general advice for that is to find a friend who understands that entire page and ask them for help installing.  Getting this game to run does not always come easy, and those instructions make that pretty clear.  Sure, I could write a smarter and friendlier patch program but that would take a lot more time than I have right now.

You have, however, helped me to decide to remove all direct links to the patch program except through that wiki so that I know everybody has at least scanned the wiki before running the patch on this troublesome game (since many people appear to be ignoring my instructions to go to the wiki and read the install instructions)... and I thank you for that help.

**Comment by juanitogan** [comment]
New version of the patch out that should be easier to get running on more systems.  Check it out.
